
services:
  bundler:
    image: accountabstraction/bundler:0.7.0
    environment:
      NAME: aa-ref-bundler-0.7.0
    command: --network $ETH_RPC_URL
    ports: [ '3000:3000' ]
    volumes:
      - ./workdir:/app/workdir:ro

