name: Test Exec

on: 
  workflow_dispatch:
    inputs:
      debug:
        description: 'Debug'
        required: false
        type: boolean

  push:
    branches: '**'

  pull_request:
    types: [opened, reopened, synchronize]

  # Allows external webhook trigger
  repository_dispatch:
    types:
      - webhook

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"

  buildMatrix:
    runs-on: ubuntu-latest
    outputs:
      version: ${{toJson(steps.versions.outputs)}}
      dirs: ${{steps.dir.outputs.dirs}}
      all: ${{toJson(steps)}}
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - run: echo "dirs=`ls dir` >> "$GITHUB_OUTPUT"
        id: dir
      - run: echo version=`ls dir/|perl -pe 's/(.*)/"$1"/'|jq -sc` >> "$GITHUB_OUTPUT"
        id: verions
      #https://stackoverflow.com/questions/59175332/using-output-from-a-previous-job-in-a-new-one-in-a-github-action

  check-matrix:
    needs: buildMatrix
    runs-on: ubuntu-latest
    steps:
      - run: echo "showing more buildMatrix ${{toJson(needs.buildMatrix.outputs)}}"

  texec:
    needs: buildMatrix
    strategy:
      matrix: ${{ needs.buildMatrix.outputs.version}}

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          show-progress: false
          # repository: ...
          # path: ...

      - id: exec
        run: echo 'out=${{matrix.version}}' | tee ${{matrix.version}}.out.txt >> $GITHUB_OUTPUT

      - uses: cloudposse/github-action-matrix-outputs-write@v1
        id: out
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.version }}
          outputs: |-
            name: ${{ steps.exec.outputs.out }}
            ## Multiline string
            # tags: ${{ toJson(steps.build.outputs) }}

      - name: Push build output to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.version}}
          path: ${{matrix.version}}.out.txt

  summary:
    runs-on: ubuntu-latest
    needs: [texec]

    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@v1
        id: read
        with:
          matrix-step-name: texec
          matrix-key: ${{ matrix.version }}
      - run: |
          cat <<EOF  
          steps.read = ${{ toJSON(steps.read)}} 
          EOF
    outputs:
        result: "${{ toJSON(steps.read.outputs) }}"


#sample from: https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
  job2:
    runs-on: ubuntu-latest
    needs:
      - job1
      - buildMatrix
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2 2=${{needs.job1.outputs.output2}}"
      - run: |
          cat <<EOF  
          all = ${{ toJson(needs) }}
          EOF


# Allow one concurrent 
concurrency:
  group: "mygroup"
  cancel-in-progress: true
