name: test matrix


on:
  push:
    branches: '**'


jobs:

  makematrix:
    outputs:
      matrix: ${{steps.setmatrix.outputs.matrix}}
    runs-on: ubuntu-latest  
    steps:
      - id: setmatrix
        run: echo matrix='[{"name":"big", "val":"11"}, {"name":"small"}]' >> $GITHUB_OUTPUT
      - name: out-${{steps.setmatrix.outputs.matrix}}
        run: echo 1
      - name: out-${{steps.setmatrix.outputs.matrix.*.name}}
        run: echo 2

  tmatrix:
    name: someName
    needs: makematrix
    strategy:
      matrix:
        include: ${{ fromJson(needs.makematrix.outputs.matrix)}}
          # - { name: big, value: 333 }
          # - { name: small, value: 1234 }
    runs-on: ubuntu-latest
    steps:
      - name: step-${{ matrix.name }}-${{matrix.value}}
        run: echo ${{ matrix }}-${{matrix.value}}
