name: test matrix


on:
  push:
    branches: '**'


jobs:

  tmatrix:
    strategy:
      matrix:
        include:
          - { name: big, value: 333 }
        name:
          - big
          - small
        value:
          - 111
          - 222
    runs-on: ubuntu-latest
    steps:
      - name: step-${{ matrix.name }}-${{matrix.value}}
        run: echo ${{ matrix.name }}-${{matrix.value}}
